//! `cargo test` writes generated client files:
//! - `client/src/generated/defs.ts`: entity kinds, animation ids, flags,
//!   class and ability numbers (so the client predicts with the same values)
//! - `client/src/generated/fixtures.json`: collision/FOV test vectors that the
//!   TypeScript ports must reproduce exactly.
//! - `client/src/generated/wire-fixtures.json`: sample snapshots as wire
//!   bytes and readable form for the client's unpack test.
//! The protocol types themselves are exported by ts-rs (`#[ts(export)]`).

use crate::collision::{step_move, MoveState};
use crate::defs::abilities::{self as ab};
use crate::defs::classes::{self, PLAYER_RADIUS};
use crate::defs::enemies;
use crate::defs::kinds::{flags, Anim, EntityKind};
use crate::dungeon::{Map, Tile, TILE};
use crate::fov::{Fov, PLAYER_FOV_RADIUS};
use crate::protocol::ClassId;
use crate::run::{DT, SNAPSHOT_EVERY, TICK_HZ};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use serde_json::json;
use std::path::PathBuf;

fn out_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../client/src/generated")
}

#[test]
fn export_defs() {
    let kinds: serde_json::Map<String, serde_json::Value> = EntityKind::ALL.iter().map(|k| (format!("{k:?}"), json!(*k as u8))).collect();
    let anims: serde_json::Map<String, serde_json::Value> = Anim::ALL.iter().map(|a| (format!("{a:?}"), json!(*a as u8))).collect();
    let class_defs: serde_json::Map<String, serde_json::Value> = ClassId::ALL
        .iter()
        .map(|c| {
            let d = classes::def(*c);
            (format!("{c:?}"), json!({ "kind": d.kind as u8, "hp": d.hp, "speed": d.speed, "primary": d.primary, "secondary": d.secondary }))
        })
        .collect();
    let abilities: serde_json::Map<String, serde_json::Value> =
        ab::ALL.iter().map(|a| (format!("{a:?}"), serde_json::to_value(ab::def(*a)).unwrap())).collect();
    let consts = json!({
        "TILE": TILE,
        "TICK_HZ": TICK_HZ,
        "DT": DT,
        "SNAPSHOT_HZ": TICK_HZ / SNAPSHOT_EVERY as f64,
        "PLAYER_RADIUS": PLAYER_RADIUS,
        "FOV_RADIUS": PLAYER_FOV_RADIUS,
        "DASH_SPEED": ab::DASH_SPEED,
        "KNOCK_DECAY": ab::KNOCK_DECAY,
        "KNOCK_MIN_SPEED": ab::KNOCK_MIN_SPEED,
        "DAGGER_RANGE": ab::DAGGER_RANGE,
        "DAGGER_COOLDOWN": ab::DAGGER_COOLDOWN,
        "HIDDEN_CRIT_MULT": ab::HIDDEN_CRIT_MULT,
        "MIMIC_HOP_CYCLE": enemies::MIMIC_HOP_CYCLE,
        "MIMIC_HOP_AIR_START": enemies::MIMIC_HOP_AIR.0,
        "MIMIC_HOP_AIR_END": enemies::MIMIC_HOP_AIR.1,
        "MIMIC_WAKE_T": enemies::MIMIC_WAKE_T,
        "OGRE_SLAM_RADIUS": enemies::OGRE_SLAM_RADIUS,
        "OGRE_SLAM_WINDUP": enemies::OGRE_SLAM_WINDUP,
        "SHALLOW_SPEED": crate::dungeon::SHALLOW_SPEED,
        "LAVA_SPEED": crate::dungeon::LAVA_SPEED,
        "FALL_TIME": crate::dungeon::FALL_TIME,
        "DROWN_TIME": crate::dungeon::DROWN_TIME,
        "POS_SCALE": crate::wire::POS_SCALE,
    });
    let fl = json!({
        "HIDDEN": flags::HIDDEN, "IMMUNE": flags::IMMUNE, "ENRAGED": flags::ENRAGED,
        "ASLEEP": flags::ASLEEP, "HURT": flags::HURT, "DEAD": flags::DEAD,
    });
    let tiles = json!({
        "Void": Tile::Void as u8, "Floor": Tile::Floor as u8, "Wall": Tile::Wall as u8,
        "DoorOpen": Tile::DoorOpen as u8, "DoorClosed": Tile::DoorClosed as u8,
        "ShallowWater": Tile::ShallowWater as u8, "DeepWater": Tile::DeepWater as u8,
        "Chasm": Tile::Chasm as u8, "Lava": Tile::Lava as u8,
    });
    let ev: serde_json::Map<String, serde_json::Value> =
        crate::wire::EV_CODES.iter().enumerate().map(|(i, n)| (n.to_string(), json!(i))).collect();
    let p = |v: &serde_json::Value| serde_json::to_string_pretty(v).unwrap();
    let ts = format!(
        "// Generated by `cargo test` (server/src/export.rs). Do not edit.\n\n\
         export const KIND = {} as const;\n\n\
         export const ANIM = {} as const;\n\n\
         export const FLAG = {} as const;\n\n\
         export const TILE_ID = {} as const;\n\n\
         export const CONST = {} as const;\n\n\
         export const CLASSES = {} as const;\n\n\
         export const ABILITIES = {} as const;\n\n\
         export const EV = {} as const;\n",
        p(&json!(kinds)),
        p(&json!(anims)),
        p(&fl),
        p(&tiles),
        p(&consts),
        p(&json!(class_defs)),
        p(&json!(abilities)),
        p(&json!(ev)),
    );
    std::fs::create_dir_all(out_dir()).unwrap();
    std::fs::write(out_dir().join("defs.ts"), ts).unwrap();
}

/// A small room with pillars, a corridor and every kind of terrain for the
/// shared test vectors.
fn fixture_map() -> Map {
    let mut m = Map::new(24, 20);
    for y in 1..19 {
        for x in 1..23 {
            m.set(x, y, Tile::Floor);
        }
    }
    for (x, y) in [(6, 5), (7, 5), (6, 6), (12, 9), (13, 9), (13, 10), (17, 4), (5, 14), (18, 15), (19, 15)] {
        m.set(x, y, Tile::Wall);
    }
    for y in 1..12 {
        m.set(10, y, Tile::Wall);
    }
    for x in 11..23 {
        m.set(x, 1, Tile::ShallowWater);
        m.set(x, 2, Tile::ShallowWater);
    }
    for x in 1..10 {
        m.set(x, 17, Tile::ShallowWater);
        m.set(x, 18, Tile::ShallowWater);
    }
    for (x, y) in [(15, 6), (16, 6), (15, 7), (16, 7)] {
        m.set(x, y, Tile::DeepWater);
    }
    for y in 5..9 {
        m.set(20, y, Tile::Chasm);
        m.set(21, y, Tile::Chasm);
    }
    for y in 13..16 {
        for x in 14..18 {
            m.set(x, y, Tile::Lava);
        }
    }
    m
}

#[test]
fn export_fixtures() {
    let map = fixture_map();
    let mut rng = ChaCha8Rng::seed_from_u64(99);
    let mut moves = Vec::new();
    for case in 0..10 {
        let (tx, ty) = if case < 6 { (3, 3 + case * 2) } else { (12, 3 + (case - 6) * 4) };
        let mut s = MoveState::at(tx as f64 * TILE + 8.0, ty as f64 * TILE + 8.0);
        let start = s;
        let speed = 60.0 + case as f64 * 5.0;
        let mut inputs = Vec::new();
        let mut out = Vec::new();
        let (mut mx, mut my) = (1i8, 0i8);
        for step in 0..400 {
            if step % 25 == 0 {
                mx = rng.gen_range(-1..=1);
                my = rng.gen_range(-1..=1);
            }
            let dash = step % 97 == 50;
            if dash {
                let a: f64 = rng.gen_range(0.0..std::f64::consts::TAU);
                s.dash_t = 0.18;
                s.dash_dx = a.cos();
                s.dash_dy = a.sin();
            }
            // A push (14-44 px, any direction) now and then, carried into terrain and walls.
            let knock = step % 97 == 20;
            if knock {
                let a: f64 = rng.gen_range(0.0..std::f64::consts::TAU);
                let v = crate::collision::knock_speed(rng.gen_range(14.0..44.0), DT);
                s.knock_vx = a.cos() * v;
                s.knock_vy = a.sin() * v;
            }
            let pushed = [s.knock_vx, s.knock_vy];
            s = step_move(&map, &s, mx, my, speed, ab::DASH_SPEED, PLAYER_RADIUS, DT);
            inputs.push(json!({
                "mx": mx, "my": my,
                "dash": if dash { json!([s.dash_dx, s.dash_dy]) } else { json!(null) },
                "knock": if knock { json!(pushed) } else { json!(null) },
            }));
            out.push(json!([s.x, s.y]));
        }
        moves.push(json!({ "start": [start.x, start.y], "speed": speed, "inputs": inputs, "out": out }));
    }
    let mut fov = Fov::new(map.w, map.h);
    let mut fovs = Vec::new();
    for (cx, cy) in [(3, 3), (8, 8), (15, 12), (11, 2), (20, 17)] {
        fov.compute(&map, cx, cy, PLAYER_FOV_RADIUS);
        let mut vis = Vec::new();
        for y in 0..map.h {
            for x in 0..map.w {
                if fov.is_visible(x, y) {
                    vis.push(y * map.w + x);
                }
            }
        }
        fovs.push(json!({ "x": cx, "y": cy, "visible": vis }));
    }
    let doc = json!({
        "w": map.w, "h": map.h, "tiles": map.tiles,
        "radius": PLAYER_RADIUS, "dt": DT, "dashSpeed": ab::DASH_SPEED, "fovRadius": PLAYER_FOV_RADIUS,
        "moves": moves, "fov": fovs,
    });
    std::fs::create_dir_all(out_dir()).unwrap();
    std::fs::write(out_dir().join("fixtures.json"), serde_json::to_string(&doc).unwrap()).unwrap();
}

/// Sample snapshots as wire bytes plus their readable form; the client's
/// `wire.test.ts` unpacks the bytes and compares.
#[test]
fn export_wire_fixtures() {
    let cases: Vec<serde_json::Value> = crate::wire::sample_snapshots()
        .iter()
        .map(|s| json!({ "bytes": crate::wire::encode_snap(s), "snap": s }))
        .collect();
    std::fs::create_dir_all(out_dir()).unwrap();
    std::fs::write(out_dir().join("wire-fixtures.json"), serde_json::to_string(&json!({ "cases": cases })).unwrap()).unwrap();
}
