//! Client <-> server messages. Encoded as MessagePack (structs as maps,
//! `EntSnap` as a compact array). Snapshots and inputs travel in the compact
//! array forms of `wire.rs`. TypeScript types are generated by ts-rs into
//! `client/src/generated/` when `cargo test` runs.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::defs::progression::{Modifiers, StatUpgrades, UpgradeStat};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum ClassId {
    Wizard,
    Paladin,
    Barbarian,
    Assassin,
}

impl ClassId {
    pub const ALL: [ClassId; 4] = [ClassId::Wizard, ClassId::Paladin, ClassId::Barbarian, ClassId::Assassin];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS)]
#[ts(export)]
pub enum BossId {
    Demon,
    Lich,
    Dragon,
}

impl BossId {
    pub const ALL: [BossId; 3] = [BossId::Demon, BossId::Lich, BossId::Dragon];
}

/// One fixed simulation step (1/60 s) of player input.
#[derive(Debug, Clone, Default, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct InputMsg {
    pub seq: u32,
    /// Movement direction, each -1, 0 or 1.
    pub mx: i8,
    pub my: i8,
    /// Aim angle in radians and distance to the cursor in pixels.
    pub aim: f32,
    pub aim_dist: f32,
    /// Shot id when the client fired its primary/secondary on this step.
    pub primary: Option<u16>,
    pub secondary: Option<u16>,
    /// How far in the past the client sees the world (rtt/2 + interpolation delay), ms.
    pub view_lag: u16,
    /// Measured round trip time, ms (used to fast-forward the player's projectiles).
    pub rtt: u16,
}

#[derive(Debug, Clone, Deserialize, Serialize, TS)]
#[serde(tag = "t")]
#[ts(export)]
pub enum ClientMsg {
    /// `token` identifies the persistent profile (issued by the server in `Profile`).
    Hello { name: String, token: Option<String> },
    CreateRun { name: String },
    JoinRun { run_id: u32 },
    LeaveRun,
    SelectClass { class: ClassId },
    SetReady { ready: bool },
    /// Host only, before the run starts. `None` = random end boss.
    SelectBoss { boss: Option<BossId> },
    /// Host only. Uses the room's chosen boss.
    StartRun,
    /// Spend profile XP on the next level of a stat (not during a run).
    BuyUpgrade { stat: UpgradeStat },
    Input(InputMsg),
    Ping { time: f64 },
    Spectate { dir: i8 },
    /// Debug mode: immortal + shortest path to the boss (if the server allows debug).
    Debug { on: bool },
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct RunSummary {
    pub id: u32,
    pub name: String,
    pub players: u8,
    pub max_players: u8,
    pub started: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct RoomPlayer {
    pub id: u32,
    pub name: String,
    pub class: ClassId,
    pub ready: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct PlayerInfo {
    /// Entity id inside the run.
    pub ent: u32,
    pub name: String,
    pub class: ClassId,
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct RunStartInfo {
    pub width: u16,
    pub height: u16,
    /// One byte per tile, row-major. See `Tile` in dungeon/mod.rs.
    #[serde(with = "serde_bytes")]
    #[ts(type = "Uint8Array")]
    pub tiles: Vec<u8>,
    pub tile_size: u16,
    /// Entity id of the receiving player.
    pub you: u32,
    pub players: Vec<PlayerInfo>,
    pub spawn_x: f64,
    pub spawn_y: f64,
    /// Progression multipliers of the receiving player (prediction must use them).
    pub mods: crate::defs::progression::Modifiers,
}

/// Compact entity state, serialized as an array:
/// `[id, kind, x, y, hp(0-255), anim, aim, anim_ms, flags, extra]`.
/// `extra` for projectiles is `(owner_id << 16) | shot_id`.
#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct EntSnap(pub u32, pub u8, pub f32, pub f32, pub u8, pub u8, pub f32, pub u16, pub u8, pub u32);

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct SelfState {
    pub alive: bool,
    pub hp: f32,
    pub max_hp: f32,
    /// Authoritative position and dash state for reconciliation.
    pub x: f64,
    pub y: f64,
    pub dash_t: f64,
    pub dash_dx: f64,
    pub dash_dy: f64,
    /// Remaining cooldowns (s).
    pub cd1: f32,
    pub cd2: f32,
    /// Remaining hide time (s), 0 when visible.
    pub hidden: f32,
    /// Entity id being spectated when dead.
    pub spectating: Option<u32>,
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct BossBar {
    pub kind: BossId,
    pub hp: f32,
    pub max_hp: f32,
    pub immune: bool,
    pub enraged: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(tag = "t")]
#[ts(export)]
pub enum Ev {
    /// Damage number. `p` = the victim is a player.
    Dmg { x: f32, y: f32, v: f32, crit: bool, p: bool },
    Heal { x: f32, y: f32, v: f32 },
    /// Explosion / area effect. k: 0 fireball, 1 heal ring, 2 fire ring, 3 dark burst, 4 dragon fireball
    Boom { x: f32, y: f32, r: f32, k: u8 },
    Died { id: u32, x: f32, y: f32, kind: u8 },
    /// A minion appears: raised skeleton (green) or summoned imp (`fire`, red).
    Raise { x: f32, y: f32, fire: bool },
    Immune { x: f32, y: f32 },
    Tile { x: u16, y: u16, v: u8 },
    Msg { text: String },
    /// Coins found at a spot (chest or kill); every living party member gets `v`.
    Coins { x: f32, y: f32, v: u32 },
    /// A hero is lost to the terrain. how: 0 falls into a chasm, 1 drowns,
    /// 2 climbs back out onto safe ground (debug mode only).
    Sink { id: u32, x: f32, y: f32, how: u8 },
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct Snapshot {
    pub tick: u32,
    /// Last processed input sequence of the receiving player.
    pub ack: u32,
    pub ents: Vec<EntSnap>,
    pub me: SelfState,
    pub boss: Option<BossBar>,
    pub ev: Vec<Ev>,
    /// Server simulation time spent per tick (ms, averaged).
    pub srv_ms: f32,
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct PlayerStats {
    pub name: String,
    pub class: ClassId,
    pub kills: u32,
    pub damage: f32,
    pub healing: f32,
    pub xp: u32,
    pub coins: u32,
    pub alive: bool,
}

#[derive(Debug, Clone, Serialize, TS)]
#[serde(tag = "t")]
#[ts(export)]
pub enum ServerMsg {
    Welcome { id: u32 },
    Lobby { runs: Vec<RunSummary> },
    /// `boss`: the host's choice of end boss, `None` = random.
    Room { run_id: u32, name: String, host: u32, players: Vec<RoomPlayer>, boss: Option<BossId> },
    /// The receiving player's persistent profile.
    Profile(ProfileInfo),
    RunStarted(RunStartInfo),
    Snap(Snapshot),
    /// `banked`: the XP was added to the profiles (false after a debug run).
    RunEnded { victory: bool, boss: BossId, time: f32, stats: Vec<PlayerStats>, banked: bool },
    Pong { time: f64 },
    Error { msg: String },
    /// Debug mode: shortest walkable path from the player to the boss (pixel waypoints).
    DebugPath { on: bool, points: Vec<(f32, f32)> },
}

#[derive(Debug, Clone, Serialize, TS)]
#[ts(export)]
pub struct ProfileInfo {
    /// Store this and send it in `Hello` to keep the profile.
    pub token: String,
    /// Unspent XP.
    pub xp: u32,
    /// Unspent coins (nothing to buy with them yet).
    pub coins: u32,
    pub upgrades: StatUpgrades,
    pub mods: Modifiers,
    /// `costs[level]` = XP for the next level; `costs.len()` = max level.
    pub costs: Vec<u32>,
}

pub fn encode(msg: &ServerMsg) -> Vec<u8> {
    rmp_serde::to_vec_named(msg).expect("encode server msg")
}

pub fn decode(bytes: &[u8]) -> Option<ClientMsg> {
    match bytes.first() {
        // A bare array is a compact input (see wire.rs).
        Some(0x90..=0x9f | 0xdc | 0xdd) => rmp_serde::from_slice::<crate::wire::InputW>(bytes).ok().map(|w| ClientMsg::Input(w.into())),
        _ => rmp_serde::from_slice(bytes).ok(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn client_msg_roundtrip() {
        let m = ClientMsg::Input(InputMsg { seq: 7, mx: 1, my: -1, aim: 0.5, primary: Some(3), ..Default::default() });
        let bytes = rmp_serde::to_vec_named(&m).unwrap();
        match decode(&bytes) {
            Some(ClientMsg::Input(i)) => {
                assert_eq!(i.seq, 7);
                assert_eq!(i.primary, Some(3));
            }
            other => panic!("unexpected {other:?}"),
        }
        let hello = rmp_serde::to_vec_named(&ClientMsg::Hello { name: "a".into(), token: None }).unwrap();
        assert!(matches!(decode(&hello), Some(ClientMsg::Hello { .. })));
    }
}
